script: script/cibuild
cache: bundler
language: ruby
sudo: false

rvm:
  - 2.1.1

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
