# Site settings
title: Freiwillige Feuerwehr Eisolzried
email: info@feuerwehr-eisolzried.de
description: "Aktuelle Neuigkeiten, Termine und Wissenswertes über die Feuerwehr Eisolzried im Bürgerhaus Deutenhausen-Eisolzried in der Gemeinde Bergkirchen"
baseurl: ""
url: "https://feuerwehr-eisolzried.de"
github_username: midzer/eisolzried

# Build settings
markdown: kramdown
permalink: pretty
keep_files: [/charts]
exclude: [vendor,config.json,Gemfile,README.md]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]
